# =========================================
#  GlowNetwork configuration
# =========================================
pack-filename=pack.zip
http-port=25566
public-host=ip
use-https=false
force-pack=true
prompt=Please accept the server resource pack
